<a href="https://colab.research.google.com/github/kirtijha014/Diagnosis-Test/blob/master/Diagnosis_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_profiling as pp

In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/RD1coder/Drug/main/Data.csv',encoding= 'unicode_escape')

In [8]:
X = data.iloc[:, 0:12].values
Y = data.iloc[:,13:33].values
#print(X)
print(Y[:,0])

['Renal Function Test' 'Serum Urea' 'None' ... 'HBS Ag ELISA' ' T4 & TSH)'
 'Serum Calcium']


In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[("encode",OneHotEncoder(sparse = False),[0,1,2,3,4,5,6,7,8,9,10,11])],remainder = "passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [10]:
x,y = Y.shape
label = []
labels = []

for k in range(y):
  temp = Y[:,k]
  #print(temp)
  for i in temp:
      if i in label:
          pass
      else:
          label.append(i)

  #print(label)
  for l in range(x):
      for i in range(len(label)):
          if (label[i]==temp[l]):
              temp[l] = i
          else :
              pass
  Y[:,k] = temp.astype(np.float)
  labels.append(label)
print(Y)
#print(len(label))


[[0.0 15.0 22.0 ... 2.0 2.0 2.0]
 [1.0 22.0 15.0 ... 2.0 2.0 2.0]
 [2.0 2.0 2.0 ... 2.0 2.0 2.0]
 ...
 [20.0 58.0 25.0 ... 2.0 2.0 2.0]
 [9.0 2.0 2.0 ... 2.0 2.0 2.0]
 [39.0 2.0 2.0 ... 2.0 2.0 2.0]]


In [11]:
print(labels[0][95])

HIV Rapid
